// src/lib/components/shared/HourlyWeather.svelte
<script lang="ts">
	import { DateTime } from 'luxon';
	import Clock from '@lucide/svelte/icons/clock';
	import SectionHeading from './SectionHeading.svelte';
	import { KYIV_TZ, getConditionTint, getWeatherIconId } from '$lib/weather';
	import type { OpenMeteoWeather } from '$lib/types';

	interface Hour {
		time: string;
		temp: number;
		precip: number;
		code: number;
	}

	let { days }: { days: OpenMeteoWeather } = $props();

	// Години від поточної і далі, максимум 24
	const hours = $derived.by<Hour[]>(() => {
		if (!days?.hourly) return [];

		const kievNowHour = DateTime.now().setZone(KYIV_TZ).startOf('hour');

		return days.hourly.time
			.map((time, idx) => ({
				time,
				temp: days.hourly.temperature_2m[idx] ?? 0,
				precip: days.hourly.precipitation[idx] ?? 0,
				code: days.hourly.weathercode[idx] ?? 0
			}))
			.filter((h) => DateTime.fromISO(h.time).setZone(KYIV_TZ).startOf('hour') >= kievNowHour)
			.slice(0, 24);
	});

	function scrollToCurrent(node: HTMLElement) {
		node.scrollIntoView({ behavior: 'smooth', inline: 'start', block: 'nearest' });
	}
</script>

<section aria-labelledby="hourly-title">
	<SectionHeading id="hourly-title" icon={Clock} title="Погодинний прогноз" />

	<ul class="scroll-x mt-5 flex gap-1" aria-label="Погодинний прогноз погоди">
		{#each hours as hour, idx (hour.time)}
			{@const isCurrent = idx === 0}
			<li
				{@attach (node) => {
					if (isCurrent) scrollToCurrent(node);
				}}
				aria-current={isCurrent ? 'true' : undefined}
				class="flex min-w-[4.25rem] shrink-0 flex-col items-center gap-3 rounded-2xl px-2 py-3 transition-colors duration-200 {isCurrent
					? 'bg-fill'
					: 'hover:bg-fill'}"
			>
				<time
					datetime={hour.time}
					class="text-[0.8125rem] font-medium text-muted-foreground tabular-nums"
				>
					{isCurrent ? 'Зараз' : DateTime.fromISO(hour.time).setZone(KYIV_TZ).toFormat('HH:mm')}
				</time>

				<svg
					class="h-7 w-7"
					style="color: {getConditionTint(hour.code)}"
					aria-hidden="true"
					viewBox="0 0 24 24"
				>
					<use href={`/icons.svg?v=10#${getWeatherIconId(hour.code)}`}></use>
				</svg>

				<!-- Ймовірність опадів показуємо лише коли вони справді є -->
				{#if hour.precip > 0}
					<span class="text-[0.6875rem] font-medium text-w-rain tabular-nums">
						{hour.precip.toFixed(1)} мм
					</span>
				{:else}
					<span class="text-[0.6875rem]">&nbsp;</span>
				{/if}

				<span class="text-[1.0625rem] font-semibold tabular-nums">
					{Math.round(hour.temp)}°
				</span>
			</li>
		{/each}
	</ul>
</section>

// components/shared/Hourly-weather.tsx
"use client";

import Image from "next/image";
import React, { useRef, useEffect } from "react";
import { DateTime } from "luxon";
interface Hour {
  time: string; // ISO строка
  temp: number;
  wind: number;
  precip: number;
  code: number;
}

interface HourlyWeatherProps {
  days: {
    hourly: {
      time: string[];
      temperature_2m: number[];
      wind_speed_10m: number[];
      precipitation: number[];
      weathercode: number[];
    };
  };
}

export const HourlyWeather: React.FC<HourlyWeatherProps> = ({ days }) => {
  if (!days || !days.hourly) return null;

  const kievNow = DateTime.now().setZone("Europe/Kyiv");

  const today = kievNow.toISODate()!; // YYYY-MM-DD, тип string
  const kievNowHour = kievNow.startOf("hour");
  const currentHourRef = useRef<HTMLDivElement | null>(null);

  // Формуємо масив годинника для поточного дня
  const hours: Hour[] = days.hourly.time
    .map((time, idx) => ({
      time,
      temp: days.hourly.temperature_2m[idx] ?? 0,
      wind: days.hourly.wind_speed_10m?.[idx] ?? 0,
      precip: days.hourly.precipitation[idx] ?? 0,
      code: days.hourly.weathercode[idx] ?? 0,
    }))
    .filter((hour) => {
      const hourDate = DateTime.fromISO(hour.time)
        .setZone("Europe/Kyiv")
        .startOf("hour");
      return hourDate >= kievNowHour; // фільтруємо години від поточного часу і далі
    })
    .slice(0, 17); // Обмежуємо до наступних 17 годин

  const getWeatherIcon = (code: number) => {
    const map: Record<number, string> = {
       0: "/0.svg",
      1: "/0.svg",
      2: "/0.svg",
      3: "/0.svg",
      45: "/45.svg",
      48: "/48.svg",
      51: "/51.svg",
      53: "/53.svg",
      55: "/1.svg",
      61: "/1.svg",
      63: "/1.svg",
      65: "/1.svg",
      66: "/1.svg",
      67: "/1.svg",
      71: "/1.svg",
      73: "/1.svg",
      75: "/1.svg",
      77: "/1.svg",
      80: "/1.svg",
      81: "/1.svg",
      82: "/1.svg",
      85: "/1.svg",
      86: "/1.svg",
      95: "/1.svg",
      96: "/1.svg",
      99: "/1.svg",
    };
    return map[code] || "/icons/unknown.svg";
  };

  // Прокрутка до поточної години після рендерингу
  useEffect(() => {
    if (currentHourRef.current) {
      currentHourRef.current.scrollIntoView({
        behavior: "smooth",
        inline: "center",
        block: "nearest",
      });
    }
  }, []);

  return (
    <div>
      <div
        className="flex gap-1 justify-evenly overflow-x-auto scroll-on-hover py-0.5"
        style={{ scrollBehavior: "smooth" }}
      >
        {hours.map((hour, idx) => {
          const hourTime = DateTime.fromISO(hour.time).setZone(
            "Europe/Kyiv"
          ).hour;
          const isCurrent = idx === 0; // перша година в списку - поточна година
          return (
            <div
              key={hour.time}
              ref={isCurrent ? currentHourRef : null} // <-- ref для поточної години
              className={`flex flex-col gap-2 items-center hover:bg-muted/70 rounded-xl text-shadow flex-shrink-0 py-0.5  ${
                isCurrent ? "bg-[color:var(--primary)] text-white" : ""
              }`}
            >
              <p
                className="text-lg font-medium"
                style={{ textShadow: "2px 2px 6px rgba(0,0,0,0.2)" }}
              >
                {hourTime}
              </p>
              <Image
                className="mx-1"
                src={getWeatherIcon(hour.code)}
                alt="Weather icon"
                width={35}
                height={38}
              />
              <p
                className="text-lg font-semibold"
                style={{ textShadow: "2px 2px 6px rgba(0,0,0,0.2)" }}
              >
                {Math.round(hour.temp)}°
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
};
