// components/shared/Footer.tsx
import React from "react";
import { Youtube, X } from "lucide-react";
import Link from "next/link";
import { APP_VERSION } from "@/lib/version";
import { Tooltip, TooltipContent, TooltipTrigger } from "../ui/tooltip";

export const Footer: React.FC = () => {
  return (
    <footer role="contentinfo" itemScope itemType="https://schema.org/WPFooter">
      <div className="max-w-7xl mx-auto px-6 py-6">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          {/* Інформація про бренд */}
          <div className="flex items-center gap-2 text-sm">
            <p className="m-0">
              <span>© {new Date().getFullYear()}</span>

              <strong className="ml-2 font-medium" itemProp="name">
                Pogodka.org
              </strong>

              <span
                className="ml-2 text-gray-500 text-xs"
                aria-label="Версія сайту"
              >
                v{APP_VERSION}
              </span>
            </p>
          </div>

          {/* Навігація */}

          <nav
            className="flex gap-6 text-sm flex-wrap justify-center"
            aria-label="Додаткова навігація"
          >
            <Tooltip>
              <TooltipTrigger asChild>
                <Link
                  href="/agreement"
                  className="border-b border-transparent hover:border-gray-500 transition-colors duration-200 underline-offset-4"
                >
                  Користувацька угода
                </Link>
              </TooltipTrigger>
              <TooltipContent side="top" align="center">
                <p>Перегляньте умови користування сайтом</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Link
                  href="/privacypolicy"
                  className="border-b border-transparent hover:border-gray-500 transition-colors duration-200 underline-offset-4"
                >
                  Політика конфіденційності
                </Link>
              </TooltipTrigger>
              <TooltipContent side="top" align="center">
                <p>Детальні умови обробки персональних даних</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Link
                  href="/support"
                  className="border-b border-transparent hover:border-gray-500 transition-colors duration-200 underline-offset-4"
                >
                  Техпідтримка
                </Link>
              </TooltipTrigger>
              <TooltipContent side="top" align="center">
                <p>Зв’яжіться з нашою службою підтримки</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Link
                  href="/ads"
                  className="border-b border-transparent hover:border-gray-500 transition-colors duration-200 underline-offset-4"
                >
                  Реклама
                </Link>
              </TooltipTrigger>
              <TooltipContent side="top" align="center">
                <p>Замовте рекламне місце на нашому сайті</p>
              </TooltipContent>
            </Tooltip>
          </nav>

          {/* Соціальні мережі */}
          <div
            className="flex gap-4"
            role="group"
            aria-label="Соціальні мережі"
          >
            <Tooltip>
              <TooltipTrigger asChild>
                <a
                  href="https://twitter.com/pogodka"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:border-gray-500 transition-colors"
                  aria-label="Twitter Pogodka.org"
                  itemProp="sameAs"
                >
                  <X size={20} aria-hidden="true" />
                </a>
              </TooltipTrigger>
              <TooltipContent side="top" align="center">
                <p>Twitter</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <a
                  href="https://www.youtube.com/@Pogodka-UA"
                  target="_blank"
                  rel="noopener noreferrer me"
                  className="hover:border-gray-500 transition-colors"
                  aria-label="YouTube Pogodka.org"
                  itemProp="sameAs"
                >
                  <Youtube size={20} aria-hidden="true" />
                </a>
              </TooltipTrigger>
              <TooltipContent side="top" align="center">
                <p>YouTube</p>
              </TooltipContent>
            </Tooltip>
          </div>
        </div>
      </div>
    </footer>
  );
};

// src/lib/components/shared/Footer.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { APP_VERSION } from '$lib/version';

	interface Props {
		/** Останній елемент ланцюжка — назва сторінки або міста */
		breadcrumb?: string;
		/** Область міста — окремий крок ланцюжка перед назвою */
		region?: string;
	}

	let { breadcrumb, region }: Props = $props();
</script>

<footer class="mt-20 bg-fill" itemscope itemtype="https://schema.org/WPFooter">
	<div class="mx-auto max-w-[980px] px-4 sm:px-6">
		<!-- Ланцюжок навігації: іконка проєкту → розділ → поточна сторінка -->
		<nav class="py-5" aria-label="Навігаційний ланцюжок">
			<ol class="flex flex-wrap items-center gap-x-2 gap-y-1 text-[0.8125rem]">
				<li class="flex items-center">
					<a
						href={resolve('/')}
						class="footer-mark flex transition-colors"
						aria-label="Pogodka — на головну"
					>
						<svg class="h-4 w-auto" viewBox="0 0 574 408" aria-hidden="true">
							<use href="/icons.svg?v=10#favicon"></use>
						</svg>
					</a>
				</li>

				<li aria-hidden="true" class="flex items-center">
					<svg
						class="h-2.5 w-2.5 text-tertiary"
						viewBox="0 0 10 10"
						fill="none"
						stroke="currentColor"
						stroke-width="1.2"
					>
						<path d="M3.5 1.5 6.5 5l-3 3.5" />
					</svg>
				</li>

				<li>
					<a
						href={resolve('/')}
						class="text-muted-foreground transition-colors hover:text-foreground hover:underline"
					>
						Прогноз погоди
					</a>
				</li>

				<!-- Область → місто: від загального до конкретного, як у ланцюжках Apple -->
				{#each [region, breadcrumb].filter(Boolean) as crumb, idx (idx)}
					<li aria-hidden="true" class="flex items-center">
						<svg
							class="h-2.5 w-2.5 text-tertiary"
							viewBox="0 0 10 10"
							fill="none"
							stroke="currentColor"
							stroke-width="1.2"
						>
							<path d="M3.5 1.5 6.5 5l-3 3.5" />
						</svg>
					</li>
					<li
						class="text-muted-foreground"
						aria-current={crumb === breadcrumb ? 'page' : undefined}
					>
						{crumb}
					</li>
				{/each}
			</ol>
		</nav>

		<!-- Полоса між ланцюжком і правовим блоком -->
		<div class="border-t border-separator"></div>

		<div class="py-5">
			<!-- Соцмережі -->
			<p class="text-[0.75rem] text-muted-foreground">
				Стежте за нами:
				<a
					href="https://www.youtube.com/@Pogodka-UA"
					target="_blank"
					rel="noopener noreferrer me"
					class="text-primary hover:underline"
					itemprop="sameAs">YouTube</a
				>.
			</p>

			<!-- Правовий рядок -->
			<div
				class="mt-2 flex flex-col gap-y-2 text-[0.75rem] text-muted-foreground sm:flex-row sm:items-center sm:gap-x-8"
			>
				<p class="m-0">
					Copyright © {new Date().getFullYear()}
					<span itemprop="name">Pogodka.org</span>. Усі права захищено.
				</p>

				<nav class="flex items-center gap-x-3" aria-label="Правова інформація">
					<a
						href={resolve('/privacypolicy')}
						class="transition-colors hover:text-foreground hover:underline"
					>
						Політика конфіденційності
					</a>
					<span class="text-separator" aria-hidden="true">|</span>
					<a
						href={resolve('/agreement')}
						class="transition-colors hover:text-foreground hover:underline"
					>
						Умови використання
					</a>
					<span class="text-separator" aria-hidden="true">|</span>
					<a
						href={resolve('/support')}
						class="transition-colors hover:text-foreground hover:underline"
					>
						Техпідтримка
					</a>
				</nav>

				<p class="m-0 flex items-center gap-1.5 sm:ml-auto">
					<span class="text-tertiary">v{APP_VERSION}</span>
					<span class="text-separator" aria-hidden="true">|</span>
					<span>Україна</span>
				</p>
			</div>
		</div>
	</div>
</footer>

<style>
	/*
		Іконка трохи темніша за сірий текст поруч, але не чорна.
		На ховер доходить до того ж кольору, що й решта посилань.
	*/
	.footer-mark {
		color: color-mix(in oklab, var(--muted-foreground) 62%, var(--foreground));
	}

	.footer-mark:hover {
		color: var(--foreground);
	}
</style>
