// components/shared/header.tsx
"use client";

import React from "react";
import { Input } from "../ui/input";
import { cn } from "@/lib/utils";
import { ModeToggle } from "./mode-toggle";
import { useDebounce } from "use-debounce";
import Link from "next/link";
import { Spinner } from "@/components/ui/spinner";
import { CircleAlert, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Props {
  className?: string;
}

type City = {
  id: number;
  slug: string;
  nameUa: string;
  nameRu: string;
  nameEn: string;
  region: string;
  latitude: number;
  longitude: number;
};

// Передзавантажуємо популярні міста відразу при імпорті модуля (один раз)
let preloadedPopular: City[] | null = null;
let preloadPromise: Promise<void> | null = null;

function preloadPopularCities() {
  if (preloadedPopular || preloadPromise) return;
  preloadPromise = fetch("/api/cities/search?q=")
    .then((r) => r.json())
    .then((data) => {
      preloadedPopular = data;
    })
    .catch(() => {});
}

// Запускаємо передзавантаження відразу
if (typeof window !== "undefined") {
  preloadPopularCities();
}

export const Header: React.FC<Props> = ({ className }) => {
  const [focused, setFocused] = React.useState(false);
  const [query, setQuery] = React.useState("");
  const [cities, setCities] = React.useState<City[]>([]);
  const [loading, setLoading] = React.useState(false);
  const [popularCities, setPopularCities] = React.useState<City[]>(
    preloadedPopular ?? [],
  );

  const [debouncedQuery] = useDebounce(query, 400);

  // Завантажуємо популярні якщо ще не завантажені
  React.useEffect(() => {
    if (preloadedPopular) {
      setPopularCities(preloadedPopular);
      return;
    }
    preloadPromise?.then(() => {
      if (preloadedPopular) setPopularCities(preloadedPopular);
    });
  }, []);

  // Пошук міст
  React.useEffect(() => {
    if (debouncedQuery.length < 2) {
      setCities([]);
      setLoading(false);
      return;
    }

    setLoading(true);
    const controller = new AbortController();

    fetch(`/api/cities/search?q=${encodeURIComponent(debouncedQuery)}`, {
      signal: controller.signal,
    })
      .then((res) => res.json())
      .then((data) => {
        setCities(data);
        setLoading(false);
      })
      .catch((err) => {
        if (err.name !== "AbortError") setLoading(false);
      });

    return () => controller.abort();
  }, [debouncedQuery]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setQuery(e.target.value);
  };

  const handleClear = () => {
    setQuery("");
    setCities([]);
  };

  const handleClose = () => {
    setFocused(false);
    handleClear();
  };

  const handleSelect = () => {
    setQuery("");
    setCities([]);
    setFocused(false);
  };

  // Що показувати у дропдауні
  const showPopular = query.length < 2;
  const displayCities = showPopular ? popularCities : cities;

  return (
    <header
      className={cn(
        "flex items-center h-14 px-4 border-border bg-background",
        className,
      )}
      role="banner"
    >
      {/* Логотип */}
      <div
        className={cn(
          "transition-all duration-200 ease-out",
          focused
            ? "opacity-0 pointer-events-none absolute"
            : "relative opacity-100",
        )}
      >
        {/* Логотип тут */}
      </div>

      {/* Затемнення фону */}
      {focused && (
        <div
          onClick={handleClose}
          className="fixed inset-0 bg-black/50 z-30"
          aria-hidden="true"
        />
      )}

      {/* Пошук */}
      <div className="flex-1 flex justify-center px-1.5 relative z-40">
        <form
          role="search"
          className="flex gap-2.5 rounded-2xl relative w-full sm:max-w-md md:max-w-lg lg:max-w-xl xl:max-w-2xl mx-auto"
          onSubmit={(e) => e.preventDefault()}
        >
          <label htmlFor="city-search" className="sr-only">
            Пошук міста по Україні
          </label>

          {/* Wrapper з піктограмою пошуку та хрестиком */}
          <div className="relative w-full">
            <Search
              className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none z-50"
              size={16}
              aria-hidden="true"
            />

            <Input
              id="city-search"
              type="search"
              autoComplete="off"
              value={query}
              onChange={handleInputChange}
              placeholder="Введіть назву міста..."
              onFocus={() => setFocused(true)}
              aria-expanded={focused}
              aria-controls="search-results"
              aria-autocomplete="list"
              className="rounded-2xl w-full pl-9 pr-9"
            />

            {/* Хрестик праворуч - тільки якщо є текст */}
            {query.length > 0 && (
              <button
                type="button"
                onClick={handleClear}
                aria-label="Очистити пошук"
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors cursor-pointer z-50"
              >
                <X size={16} />
              </button>
            )}
          </div>

          {/* Кнопка закрити (X) — з'являється під час фокусування */}
          <div
            className={cn(
              "transition-all duration-200 ease-out",
              focused
                ? "w-9 opacity-100 translate-x-0"
                : "w-0 opacity-0 translate-x-3 pointer-events-none",
            )}
          >
            <Button
              type="button"
              onClick={handleClose}
              variant="outline"
              size="icon"
              aria-label="Закрити пошук"
              className="rounded-full cursor-pointer"
            >
              <X />
            </Button>
          </div>
        </form>

        {/* Дропдаун із результатами */}
        <div
          id="search-results"
          role="listbox"
          aria-label="Результати пошуку міст"
          className={cn(
            "absolute w-full bg-muted rounded-2xl shadow-md transition-all duration-200 invisible opacity-0 top-14",
            "max-w-sm sm:max-w-md md:max-w-lg lg:max-w-xl xl:max-w-2xl",
            focused && "visible opacity-100 top-11",
          )}
        >
          {/* Скрольований контейнер */}
          <style>{`
            .cities-scroll::-webkit-scrollbar { width: 4px; }
            .cities-scroll::-webkit-scrollbar-thumb { background: transparent; border-radius: 4px; transition: background 0.2s; }
            .cities-scroll:hover::-webkit-scrollbar-thumb { background: hsl(var(--border)); }
            .cities-scroll { scrollbar-width: none; }
            .cities-scroll:hover { scrollbar-width: thin; scrollbar-color: hsl(var(--border)) transparent; }
          `}</style>
          {/* Завантаження */}
          {loading && (
            <p className="flex items-center gap-1 px-3 py-2 rounded-2xl">
              <Spinner className="size-5" />
              Пошук...
            </p>
          )}

          {/* Список міст зі скролом */}
          {!loading && displayCities.length > 0 && (
            <div className="overflow-hidden rounded-2xl">
              <div
                className="cities-scroll overflow-y-auto"
                style={{ maxHeight: "calc(7 * 40px)" }}
              >
                {displayCities.map((city) => (
                  <Link
                    key={city.id}
                    href={`/pohoda/${city.slug}`}
                    role="option"
                    onClick={handleSelect}
                    prefetch={false}
                  >
                    <div
                      className="px-3 py-2 hover:bg-primary/10 whitespace-nowrap overflow-hidden text-ellipsis"
                      style={{ height: 40, lineHeight: "24px" }}
                    >
                      🇺🇦 {city.nameUa},{" "}
                      <span className="text-muted-foreground">
                        {city.region}
                      </span>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          )}

          {/* Нічого не знайдено */}
          {!loading && !showPopular && cities.length === 0 && (
            <p className="flex gap-1 items-center px-3 py-2 rounded-2xl text-red-500">
              <CircleAlert size={18} />
              Місто не знайдено
            </p>
          )}
        </div>
      </div>

      {/* Перемикач теми */}
      <div
        className={cn(
          "transition-all duration-300 ease-in-out z-20",
          focused
            ? "opacity-0 pointer-events-none absolute right-4"
            : "relative opacity-100",
        )}
      >
        <ModeToggle />
      </div>
    </header>
  );
};

// src/lib/components/shared/Header.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { goto } from '$app/navigation';
	import { cn } from '$lib/utils';
	import SettingsMenu from './SettingsMenu.svelte';
	import Search from '@lucide/svelte/icons/search';
	import X from '@lucide/svelte/icons/x';
	import LoaderCircle from '@lucide/svelte/icons/loader-circle';
	import CircleAlert from '@lucide/svelte/icons/circle-alert';
	import type { CitySearchResult } from '$lib/types';

	let { class: className }: { class?: string } = $props();

	let focused = $state(false);
	let query = $state('');
	let cities = $state<CitySearchResult[]>([]);
	let loading = $state(false);
	let popularCities = $state<CitySearchResult[]>([]);
	let inputEl = $state<HTMLInputElement | null>(null);
	// Підсвічений рядок у випадайці (для стрілок на клавіатурі)
	let activeIndex = $state(-1);

	// Популярні міста підвантажуємо один раз
	$effect(() => {
		let cancelled = false;

		fetch('/api/cities/search?q=')
			.then((r) => r.json())
			.then((data: CitySearchResult[]) => {
				if (!cancelled) popularCities = data;
			})
			.catch(() => {});

		return () => {
			cancelled = true;
		};
	});

	// Пошук із дебаунсом 400 мс
	$effect(() => {
		const value = query.trim();

		if (value.length < 2) {
			cities = [];
			loading = false;
			return;
		}

		loading = true;
		const controller = new AbortController();

		const timer = setTimeout(() => {
			fetch(`/api/cities/search?q=${encodeURIComponent(value)}`, { signal: controller.signal })
				.then((res) => res.json())
				.then((data: CitySearchResult[]) => {
					cities = data;
					loading = false;
				})
				.catch((err) => {
					if (err.name !== 'AbortError') loading = false;
				});
		}, 400);

		return () => {
			clearTimeout(timer);
			controller.abort();
		};
	});

	const showPopular = $derived(query.trim().length < 2);
	const displayCities = $derived(showPopular ? popularCities : cities);

	// Новий список — скидаємо підсвічування
	$effect(() => {
		void displayCities;
		activeIndex = -1;
	});

	function clear() {
		query = '';
		cities = [];
		inputEl?.focus();
	}

	function close() {
		focused = false;
		query = '';
		cities = [];
		activeIndex = -1;
	}

	function cityHref(city: CitySearchResult) {
		return resolve('/pohoda/[city]', { city: city.slug });
	}

	// Enter або кнопка пошуку — відкриваємо підсвічене місто, інакше перше в списку
	function submit(event: SubmitEvent) {
		event.preventDefault();
		const target = displayCities[activeIndex] ?? (showPopular ? undefined : displayCities[0]);
		if (!target) return;
		close();
		inputEl?.blur();
		goto(cityHref(target));
	}

	function onKeydown(event: KeyboardEvent) {
		if (!focused) return;

		if (event.key === 'ArrowDown') {
			event.preventDefault();
			activeIndex = Math.min(activeIndex + 1, displayCities.length - 1);
		} else if (event.key === 'ArrowUp') {
			event.preventDefault();
			activeIndex = Math.max(activeIndex - 1, -1);
		} else if (event.key === 'Escape') {
			close();
			inputEl?.blur();
		}
	}

	// Підсвічений рядок прокручуємо у видиму область списку
	function keepInView(node: HTMLElement, active: boolean) {
		const apply = (isActive: boolean) => {
			if (isActive) node.scrollIntoView({ block: 'nearest' });
		};
		apply(active);
		return { update: apply };
	}
</script>

<!-- Шапка не липка: прокручується разом зі сторінкою -->
<header class={cn('relative z-50 bg-background', className)}>
	<div
		class="mx-auto grid h-14 max-w-[980px] grid-cols-[auto_1fr_auto] items-center gap-3 px-4 sm:px-6 md:grid-cols-[1fr_minmax(0,26rem)_1fr] md:gap-6"
	>
		<!-- Логотип і назва — одним кольором -->
		<a
			href={resolve('/')}
			class="flex items-center gap-2 justify-self-start text-foreground transition-opacity hover:opacity-70"
			aria-label="Pogodka — на головну"
		>
			<svg class="h-6 w-auto shrink-0" viewBox="0 0 574 408" aria-hidden="true">
				<use href="/icons.svg?v=10#favicon"></use>
			</svg>
			<span class="text-[20px] font-semibold tracking-[-0.02em] max-[380px]:hidden">Pogodka</span>
		</a>

		<!-- Пошук: поле з хрестиком і приєднана кнопка -->
		<div class="relative w-full">
			<!-- Поле й кнопка — одна група: при фокусі обводка primary охоплює обидва -->
			<form
				role="search"
				class="flex overflow-hidden rounded-md border border-separator transition-colors focus-within:border-primary"
				onsubmit={submit}
			>
				<label for="city-search" class="sr-only">Пошук міста по Україні</label>

				<div class="relative min-w-0 flex-1">
					<input
						bind:this={inputEl}
						bind:value={query}
						id="city-search"
						type="search"
						autocomplete="off"
						placeholder="Пошук міста"
						onfocus={() => (focused = true)}
						onkeydown={onKeydown}
						role="combobox"
						aria-expanded={focused}
						aria-controls="search-results"
						aria-autocomplete="list"
						aria-activedescendant={activeIndex >= 0 ? `city-option-${activeIndex}` : undefined}
						class="h-9 w-full border-0 bg-background pr-8 pl-3 text-[15px] outline-none placeholder:text-tertiary focus:outline-none focus-visible:outline-none"
					/>

					{#if query.length > 0}
						<button
							type="button"
							onclick={clear}
							aria-label="Очистити пошук"
							class="absolute top-1/2 right-2 flex size-5 -translate-y-1/2 cursor-pointer items-center justify-center text-tertiary transition-colors hover:text-foreground"
						>
							<X size={16} />
						</button>
					{/if}
				</div>

				<button
					type="submit"
					aria-label="Знайти"
					class="flex h-9 w-11 shrink-0 cursor-pointer items-center justify-center border-l border-separator bg-fill outline-none focus-visible:outline-none text-muted-foreground transition-colors hover:bg-[color-mix(in_oklab,var(--fill),var(--foreground)_6%)] hover:text-foreground"
				>
					<Search size={17} />
				</button>
			</form>

			<!-- Випадайка результатів -->
			{#if focused}
				<div
					id="search-results"
					role="listbox"
					aria-label="Результати пошуку міст"
					class="absolute inset-x-0 top-[calc(100%+4px)] z-50 overflow-hidden rounded-md border border-separator bg-popover shadow-[0_8px_24px_rgba(0,0,0,0.12)]"
				>
					{#if loading}
						<p class="flex items-center gap-2 px-3 py-3 text-[15px] text-muted-foreground">
							<LoaderCircle size={16} class="animate-spin" />
							Пошук…
						</p>
					{:else if displayCities.length > 0}
						<ul class="scroll-y max-h-[22rem]">
							{#each displayCities as city, idx (city.id)}
								<li use:keepInView={idx === activeIndex}>
									<a
										id={`city-option-${idx}`}
										href={cityHref(city)}
										role="option"
										aria-selected={idx === activeIndex}
										onclick={close}
										onmouseenter={() => (activeIndex = idx)}
										data-sveltekit-preload-data="off"
										class="block truncate px-3 py-2.5 text-[15px] {idx === activeIndex
											? 'bg-fill'
											: ''}"
									>
										<span class="text-foreground">{city.nameUa}</span><span
											class="text-muted-foreground">, {city.region}</span
										>
									</a>
								</li>
							{/each}
						</ul>
					{:else}
						<p class="flex items-center gap-2 px-3 py-3 text-[15px] text-muted-foreground">
							<CircleAlert size={16} />
							Місто не знайдено
						</p>
					{/if}
				</div>
			{/if}
		</div>

		<!-- Налаштування -->
		<div class="justify-self-end">
			<SettingsMenu />
		</div>
	</div>
</header>

<!-- Клік поза випадайкою закриває її -->
{#if focused}
	<button
		type="button"
		onclick={close}
		tabindex="-1"
		aria-hidden="true"
		class="fixed inset-0 z-40 cursor-default"
	></button>
{/if}
