// src/routes/support/+page.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import { applyAction, enhance } from '$app/forms';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { toast } from 'svelte-sonner';
	import { Button } from '$lib/components/ui/button';
	import * as Field from '$lib/components/ui/field';
	import { Input } from '$lib/components/ui/input';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Spinner } from '$lib/components/ui/spinner';
	import { cn } from '$lib/utils';
	import { emptyErrors, validateSupport, type SupportErrors } from '$lib/supportSchema';
	import type { ActionData } from './$types';

	let { form }: { form: ActionData } = $props();

	// Значення з невдалої відправки потрібні лише при першому рендері (варіант без JS)
	const initial = untrack(() => form?.values);

	let email = $state(initial?.email ?? '');
	let subject = $state(initial?.subject ?? '');
	let message = $state(initial?.message ?? '');
	let loading = $state(false);

	let errors = $state<SupportErrors>({ ...emptyErrors });
	let isValid = $state(false);
	let touched = $state({ email: false, subject: false, message: false });

	// Валідація на кожну зміну полів
	$effect(() => {
		const values = { email, subject, message };
		let cancelled = false;

		validateSupport(values).then((result) => {
			if (cancelled) return;
			errors = result.errors;
			isValid = result.valid;
		});

		return () => {
			cancelled = true;
		};
	});
</script>

<svelte:head>
	<title>Техпідтримка — Pogodka</title>
	<meta name="description" content="Зв’яжіться зі службою підтримки Pogodka." />
	<meta name="robots" content="noindex, follow" />
</svelte:head>

<form
	method="POST"
	use:enhance={() => {
		loading = true;

		return async ({ result }) => {
			loading = false;

			if (result.type === 'success') {
				email = '';
				subject = '';
				message = '';
				touched = { email: false, subject: false, message: false };
				errors = { ...emptyErrors };
				toast.success('Готово! Повідомлення надіслано.');
				await goto(resolve('/'), { replaceState: true });
				return;
			}

			if (result.type === 'failure') {
				toast.error(String(result.data?.message ?? 'Помилка відправки.'));
				return;
			}

			await applyAction(result);
		};
	}}
>
	<Field.Group class="flex min-h-screen flex-col items-center justify-center gap-4 px-4">
		<!-- Поле Email -->
		<Field.Field
			class={cn(
				'w-full max-w-md transition-colors',
				touched.email && errors.email
					? 'border-red-500 focus:border-red-500'
					: 'border-gray-300 focus:border-primary'
			)}
		>
			<Field.Label for="support-email">Email</Field.Label>
			<Input
				id="support-email"
				name="email"
				type="email"
				placeholder="Email"
				bind:value={email}
				onblur={() => (touched.email = true)}
				aria-invalid={Boolean(errors.email) && touched.email}
				class="transition-colors"
			/>
			<Field.Description class="mt-1 text-sm">
				{touched.email && errors.email
					? errors.email
					: 'Введіть email, куди нам надіслати відповідь.'}
			</Field.Description>
		</Field.Field>

		<!-- Поле Тема повідомлення -->
		<Field.Field
			class={cn(
				'w-full max-w-md transition-colors',
				touched.subject && errors.subject
					? 'border-red-500 focus:border-red-500'
					: 'border-gray-300 focus:border-primary'
			)}
		>
			<Field.Label for="support-subject">Тема повідомлення</Field.Label>
			<Input
				id="support-subject"
				name="subject"
				type="text"
				placeholder="Тема"
				bind:value={subject}
				onblur={() => (touched.subject = true)}
				aria-invalid={Boolean(errors.subject) && touched.subject}
				class="transition-colors"
			/>
			<Field.Description class="mt-1 text-sm">
				{touched.subject && errors.subject ? errors.subject : 'Введіть тему повідомлення.'}
			</Field.Description>
		</Field.Field>

		<!-- Поле Повідомлення -->
		<Field.Field
			class={cn(
				'w-full max-w-md transition-colors',
				touched.message && errors.message
					? 'border-red-500 focus:border-red-500'
					: 'border-gray-300 focus:border-primary'
			)}
		>
			<Field.Label for="support-message">Ваше питання</Field.Label>
			<Textarea
				id="support-message"
				name="message"
				placeholder="Введіть тут своє повідомлення."
				bind:value={message}
				onblur={() => (touched.message = true)}
				aria-invalid={Boolean(errors.message) && touched.message}
				class="transition-colors"
			/>
			<Field.Description class="mt-1 text-sm">
				{touched.message && errors.message ? errors.message : 'Введіть тут своє питання.'}
			</Field.Description>
		</Field.Field>

		<!-- Кнопка відправки -->
		<Field.Field class="w-full max-w-md">
			<Button type="submit" class="w-full" disabled={!isValid || loading}>
				{#if loading}
					<Spinner class="size-6" /> Відправка...
				{:else}
					Відправити
				{/if}
			</Button>
		</Field.Field>
	</Field.Group>
</form>

// app/support/page.tsx
"use client";

import React from "react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { Button } from "@/components/ui/button";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Spinner } from "@/components/ui/spinner";
import * as Yup from "yup";
import { cn } from "@/lib/utils";

// Валідація
const SupportSchema = Yup.object({
  email: Yup.string().email("Невірний email").required("Email обовʼязковий"),
  subject: Yup.string()
    .min(3, "Мінімум 3 символи")
    .max(100, "Максимум 100 символів")
    .required("Тема обовʼязкова"),
  message: Yup.string()
    .min(10, "Мінімум 10 символів")
    .max(1000, "Максимум 1000 символів")
    .required("Повідомлення обовʼязкове"),
});

export default function SupportPage() {
  const router = useRouter();
  const [email, setEmail] = React.useState("");
  const [subject, setSubject] = React.useState("");
  const [message, setMessage] = React.useState("");
  const [loading, setLoading] = React.useState(false);

  const [errors, setErrors] = React.useState({
    email: "",
    subject: "",
    message: "",
  });
  const [touched, setTouched] = React.useState({
    email: false,
    subject: false,
    message: false,
  });
  const [isValid, setIsValid] = React.useState(false);

// Автоматична валідація при зміні полів
  React.useEffect(() => {
    async function validate() {
      try {
        await SupportSchema.validate(
          { email, subject, message },
          { abortEarly: false },
        );
        setErrors({ email: "", subject: "", message: "" });
        setIsValid(true);
      } catch (err: any) {
        const newErrors: any = { email: "", subject: "", message: "" };
        if (err.inner) {
          err.inner.forEach((e: any) => {
            newErrors[e.path] = e.message;
          });
        }
        setErrors(newErrors);
        setIsValid(false);
      }
    }
    validate();
  }, [email, subject, message]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!isValid) return;

    setLoading(true);
    try {
      const res = await fetch("/api/support", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, subject, message }),
      });

      if (!res.ok) throw new Error();
      router.replace("/");
      setEmail("");
      setSubject("");
      setMessage("");
      setTouched({ email: false, subject: false, message: false });
      setErrors({ email: "", subject: "", message: "" });
      toast.success("Готово! Повідомлення надіслано.");
    } catch {
      toast.error("Помилка відправки.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <FieldGroup className="min-h-screen  flex flex-col items-center justify-center px-4 gap-4">
        {/* Поле Email */}

        <Field
          className={cn(
            "w-full max-w-md transition-colors",
            touched.email && errors.email
              ? "border-red-500 focus:border-red-500"
              : "border-gray-300 focus:border-primary",
          )}
        >
          <FieldLabel>Email</FieldLabel>
          <Input
            type="email"
            placeholder="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            onBlur={() => setTouched((prev) => ({ ...prev, email: true }))}
            aria-invalid={!!errors.email && touched.email}
            className="transition-colors"
          />
          <FieldDescription className="text-sm mt-1">
            {touched.email && errors.email
              ? errors.email
              : "Введіть email, куди нам надіслати відповідь."}
          </FieldDescription>
        </Field>

        {/* Поле Тема повідомлення */}
        <Field
          className={cn(
            "w-full max-w-md transition-colors",
            touched.subject && errors.subject
              ? "border-red-500 focus:border-red-500"
              : "border-gray-300 focus:border-primary",
          )}
        >
          <FieldLabel>Тема повідомлення</FieldLabel>
          <Input
            type="text"
            placeholder="Тема"
            value={subject}
            onChange={(e) => setSubject(e.target.value)}
            onBlur={() => setTouched((prev) => ({ ...prev, subject: true }))}
            aria-invalid={!!errors.subject && touched.subject}
            className="transition-colors"
          />
          <FieldDescription className="text-sm mt-1">
            {touched.subject && errors.subject
              ? errors.subject
              : "Введіть тему повідомлення."}
          </FieldDescription>
        </Field>

        {/* Поле Повідомлення */}
        <Field
          className={cn(
            "w-full max-w-md transition-colors",
            touched.message && errors.message
              ? "border-red-500 focus:border-red-500"
              : "border-gray-300 focus:border-primary",
          )}
        >
          <FieldLabel>Ваше питання</FieldLabel>
          <Textarea
            placeholder="Введіть тут своє повідомлення."
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            onBlur={() => setTouched((prev) => ({ ...prev, message: true }))}
            aria-invalid={!!errors.message && touched.message}
            className="transition-colors"
          />
          <FieldDescription className="text-sm mt-1">
            {touched.message && errors.message
              ? errors.message
              : "Введіть тут своє питання."}
          </FieldDescription>
        </Field>

        {/* Кнопка Відправки */}
        <Field className="w-full max-w-md">
          <Button
            type="submit"
            className="w-full"
            disabled={!isValid || loading}
          >
            {loading ? (
              <>
                <Spinner className="size-6" /> Відправка...
              </>
            ) : (
              "Відправити"
            )}
          </Button>
        </Field>
      </FieldGroup>
    </form>
  );
}
